server:
  port: 7777
spring:
  boot:
    admin:
      client:
        url: http://localhost:8888
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
          lower-case-service-id: true
  main:
    web-application-type: reactive
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka