version: '3.8'
services:
  eureka-server:
    build:
      context: ./Eureka
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8762:8762"
    environment:
      - SPRING_PROFILES_ACTIVE=cloud
    networks:
      - my-network

  api-gateway:
    build:
      context: ./Gateway-Api
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "7777:7777"
    environment:
      - SPRING_PROFILES_ACTIVE=cloud
    depends_on:
      - eureka-server
    networks:
      - my-network

  doctor-service:
    build:
      context: ./Doctor
      dockerfile: Dockerfile
    container_name: doctor-service
    ports:
      - "5056:5051"
    environment:
      - SPRING_PROFILES_ACTIVE=cloud
    depends_on:
      - eureka-server
    networks:
      - my-network

  patient-service:
    build:
      context: ./patient
      dockerfile: Dockerfile
    container_name: patient-service
    ports:
      - "5057:5053"
    environment:
      - SPRING_PROFILES_ACTIVE=cloud
    depends_on:
      - eureka-server
    networks:
      - my-network

  payment-service:
    build:
      context: ./Payment
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "5058:5052"
    environment:
      - SPRING_PROFILES_ACTIVE=cloud
    depends_on:
      - eureka-server
    networks:
      - my-network

networks:
  my-network:
    driver: bridge