server :
  port: 8762

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    show-details: always

spring:
  application:
    name:  EUREKA-SERVER
  boot:
    admin:
      client:
        url: http://localhost:8888

eureka :
  client :
    registerwitheureka: false
    fetchregistry: false