server:
  port: 5052
  servlet:
    context-path: /payment



spring:
  application:
    name: PAYMENT-SERVICE
  boot:
    admin:
      client:
        url: http://localhost:8888


  datasource:
    url: jdbc:h2:file:./Payment/database/payment_db
    driverClassName: org.h2.Driver
    username: root
    password:

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate :
      ddl-auto : update


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
management:
  health:
    show-details: always
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  ### Spring boot admin
  endpoints:
    web:
      exposure:
        include: "*"
  ### Spring boot admin
